local opt = vim.opt
opt.number = true
opt.cursorline = true
opt.swapfile = false
opt.wrap = false
opt.linebreak = true
opt.expandtab = true
opt.shiftwidth = 0
opt.tabstop = 2
opt.mouse = 'nv'
opt.cmdheight = 0
opt.pumheight = 15
opt.scrolloff = 8
opt.sidescrolloff = 8
opt.signcolumn = 'yes'
-- opt.winborder = 'rounded'
opt.fillchars = {
	stl = ' ',
	stlnc = '-',
	msgsep = ' ',
	foldopen = '',
	foldclose = '',
	fold = ' ',
	foldsep = ' ',
	diff = '╱',
	eob = ' ',
}
opt.list = true
opt.listchars = 'tab:»·,nbsp:+,trail:·,extends:→,precedes:←'
opt.inccommand = 'split'
opt.ignorecase = true
opt.smartcase = true
opt.hlsearch = false
