local opt = vim.opt
opt.number = true
opt.cursorline = true
opt.swapfile = false
opt.expandtab = true
opt.shiftround = true
opt.shiftwidth = 0
opt.tabstop = 2
opt.mouse = 'nv'
opt.cmdheight = 0
opt.pumheight = 10
opt.pumwidth = 10
opt.scrolloff = 8
opt.sidescrolloff = 8
opt.foldlevel = 99
-- opt.grepformat = '%f:%l:%c:%m'
-- opt.grepprg = 'rg --vimgrep'
opt.fillchars = {
	stl = ' ',
	stlnc = '-',
	msgsep = ' ',
	foldopen = '',
	foldclose = '',
	fold = ' ',
	foldsep = ' ',
	diff = '╱',
	eob = ' ',
}
opt.list = true
opt.listchars = 'tab:» ,nbsp:+,trail:·,extends:→,precedes:←'
opt.linebreak = true
opt.wrap = false
-- opt.inccommand = 'split'
opt.ignorecase = true
opt.smartcase = true
opt.hlsearch = false
opt.termguicolors = true
