-- Packages --
vim.pack.add({
	{ src = 'https://github.com/neanias/everforest-nvim' },
	{ src = 'https://github.com/nvim-treesitter/nvim-treesitter' },
	{ src = 'https://github.com/neovim/nvim-lspconfig' },
	{ src = 'https://github.com/mason-org/mason.nvim' },
	{ src = 'https://github.com/mason-org/mason-lspconfig.nvim' },
	{ src = 'https://github.com/nvim-mini/mini.ai' },
	{ src = 'https://github.com/nvim-mini/mini.completion' },
	{ src = 'https://github.com/nvim-mini/mini.cmdline' },
	{ src = 'https://github.com/nvim-mini/mini.files' },
	{ src = 'https://github.com/nvim-mini/mini.icons' },
	{ src = 'https://github.com/nvim-mini/mini.keymap' },
	{ src = 'https://github.com/nvim-mini/mini.notify' },
	{ src = 'https://github.com/nvim-mini/mini.pick' },
	{ src = 'https://github.com/nvim-mini/mini.snippets' },
	{ src = 'https://github.com/nvim-mini/mini.statusline' },
	{ src = 'https://github.com/nvim-mini/mini.tabline' },
	-- { src = "https://github.com/farmergreg/vim-lastplace" },
	-- { src = "https://github.com/Darazaki/indent-o-matic" },
}, { confirm = false })
